const demoArray = [
  [
    { time: 0, timeShifted: 0, volume: 96, index: 0 },
    { time: 10, timeShifted: 0, volume: 61, index: 1 },
    { time: 20, timeShifted: 0, volume: 58, index: 2 },
    { time: 30, timeShifted: 0, volume: 88, index: 3 },
    { time: 40, timeShifted: 0, volume: 97, index: 4 },
    { time: 50, timeShifted: 0, volume: 63, index: 5 },
    { time: null, timeShifted: 0, volume: 64, index: 6 },
    { time: 70, timeShifted: 0, volume: 89, index: 7 },
    { time: 80, timeShifted: 0, volume: 98, index: 8 },
    { time: 90, timeShifted: 0, volume: 59, index: 9 },
    { time: 100, timeShifted: 0, volume: 65, index: 10 },
    { time: 110, timeShifted: 0, volume: 88, index: 11 },
    { time: 120, timeShifted: 0, volume: 97, index: 12 },
    { time: 130, timeShifted: 0, volume: 61, index: 13 },
    { time: null, timeShifted: 0, volume: 64, index: 14 },
    { time: 150, timeShifted: 0, volume: 91, index: 15 }
  ],
  [
    { time: null, timeShifted: 0, volume: 80, index: 0 },
    { time: null, timeShifted: 0, volume: 80, index: 1 },
    { time: null, timeShifted: 0, volume: 80, index: 2 },
    { time: null, timeShifted: 0, volume: 80, index: 3 },
    { time: null, timeShifted: 0, volume: 80, index: 4 },
    { time: null, timeShifted: 0, volume: 80, index: 5 },
    { time: 60, timeShifted: 0, volume: 80, index: 6 },
    { time: null, timeShifted: 0, volume: 80, index: 7 },
    { time: null, timeShifted: 0, volume: 80, index: 8 },
    { time: null, timeShifted: 0, volume: 80, index: 9 },
    { time: null, timeShifted: 0, volume: 80, index: 10 },
    { time: null, timeShifted: 0, volume: 80, index: 11 },
    { time: null, timeShifted: 0, volume: 80, index: 12 },
    { time: null, timeShifted: 0, volume: 80, index: 13 },
    { time: 140, timeShifted: 0, volume: 80, index: 14 },
    { time: null, timeShifted: 0, volume: 80, index: 15 }
  ],
  [
    { time: null, timeShifted: 0, volume: 80, index: 0 },
    { time: null, timeShifted: 0, volume: 80, index: 1 },
    { time: null, timeShifted: 0, volume: 80, index: 2 },
    { time: null, timeShifted: 0, volume: 80, index: 3 },
    { time: null, timeShifted: 0, volume: 80, index: 4 },
    { time: null, timeShifted: 0, volume: 80, index: 5 },
    { time: null, timeShifted: 0, volume: 80, index: 6 },
    { time: null, timeShifted: 0, volume: 80, index: 7 },
    { time: null, timeShifted: 0, volume: 80, index: 8 },
    { time: null, timeShifted: 0, volume: 80, index: 9 },
    { time: null, timeShifted: 0, volume: 80, index: 10 },
    { time: null, timeShifted: 0, volume: 80, index: 11 },
    { time: null, timeShifted: 0, volume: 80, index: 12 },
    { time: null, timeShifted: 0, volume: 80, index: 13 },
    { time: null, timeShifted: 0, volume: 80, index: 14 },
    { time: null, timeShifted: 0, volume: 80, index: 15 }
  ],
  [
    { time: 0, timeShifted: 0, volume: 38, index: 0 },
    { time: null, timeShifted: 0, volume: 80, index: 1 },
    { time: 20, timeShifted: 0, volume: 33, index: 2 },
    { time: null, timeShifted: 0, volume: 80, index: 3 },
    { time: 40, timeShifted: 0, volume: 38, index: 4 },
    { time: 52, timeShifted: 2, volume: 29, index: 5 },
    { time: null, timeShifted: 0, volume: 80, index: 6 },
    { time: null, timeShifted: 0, volume: 80, index: 7 },
    { time: 80, timeShifted: 0, volume: 40, index: 8 },
    { time: 94, timeShifted: 4, volume: 31, index: 9 },
    { time: 107, timeShifted: 7, volume: 30, index: 10 },
    { time: null, timeShifted: 0, volume: 80, index: 11 },
    { time: 120, timeShifted: 0, volume: 37, index: 12 },
    { time: null, timeShifted: 0, volume: 80, index: 13 },
    { time: null, timeShifted: 0, volume: 80, index: 14 },
    { time: null, timeShifted: 0, volume: 80, index: 15 }
  ],
  [
    { time: 0, timeShifted: 0, volume: 89, index: 0 },
    { time: null, timeShifted: 0, volume: 80, index: 1 },
    { time: null, timeShifted: 0, volume: 80, index: 2 },
    { time: 30, timeShifted: 0, volume: 46, index: 3 },
    { time: null, timeShifted: 0, volume: 80, index: 4 },
    { time: null, timeShifted: 0, volume: 80, index: 5 },
    { time: 61, timeShifted: 1, volume: 80, index: 6 },
    { time: null, timeShifted: 0, volume: 80, index: 7 },
    { time: null, timeShifted: 0, volume: 80, index: 8 },
    { time: null, timeShifted: 0, volume: 80, index: 9 },
    { time: 100, timeShifted: 0, volume: 78, index: 10 },
    { time: null, timeShifted: 0, volume: 80, index: 11 },
    { time: null, timeShifted: 0, volume: 80, index: 12 },
    { time: 130, timeShifted: 0, volume: 68, index: 13 },
    { time: null, timeShifted: 0, volume: 80, index: 14 },
    { time: null, timeShifted: 0, volume: 80, index: 15 }
  ],
  [
    { time: null, timeShifted: 0, volume: 80, index: 0 },
    { time: null, timeShifted: 0, volume: 80, index: 1 },
    { time: null, timeShifted: 0, volume: 80, index: 2 },
    { time: null, timeShifted: 0, volume: 80, index: 3 },
    { time: 40, timeShifted: 0, volume: 75, index: 4 },
    { time: null, timeShifted: 0, volume: 80, index: 5 },
    { time: 60, timeShifted: 0, volume: 64, index: 6 },
    { time: null, timeShifted: 0, volume: 80, index: 7 },
    { time: null, timeShifted: 0, volume: 80, index: 8 },
    { time: null, timeShifted: 0, volume: 80, index: 9 },
    { time: null, timeShifted: 0, volume: 80, index: 10 },
    { time: null, timeShifted: 0, volume: 80, index: 11 },
    { time: 120, timeShifted: 0, volume: 80, index: 12 },
    { time: 133, timeShifted: 3, volume: 80, index: 13 },
    { time: 146, timeShifted: 6, volume: 80, index: 14 },
    { time: null, timeShifted: 0, volume: 80, index: 15 }
  ],
  [
    { time: 0, timeShifted: 0, volume: 80, index: 0 },
    { time: null, timeShifted: 0, volume: 80, index: 1 },
    { time: null, timeShifted: 0, volume: 80, index: 2 },
    { time: null, timeShifted: 0, volume: 80, index: 3 },
    { time: null, timeShifted: 0, volume: 80, index: 4 },
    { time: null, timeShifted: 0, volume: 80, index: 5 },
    { time: null, timeShifted: 0, volume: 80, index: 6 },
    { time: null, timeShifted: 0, volume: 80, index: 7 },
    { time: 80, timeShifted: 0, volume: 80, index: 8 },
    { time: null, timeShifted: 0, volume: 80, index: 9 },
    { time: null, timeShifted: 0, volume: 80, index: 10 },
    { time: null, timeShifted: 0, volume: 80, index: 11 },
    { time: null, timeShifted: 0, volume: 80, index: 12 },
    { time: null, timeShifted: 0, volume: 80, index: 13 },
    { time: null, timeShifted: 0, volume: 80, index: 14 },
    { time: null, timeShifted: 0, volume: 80, index: 15 }
  ],
  [
    { time: 0, timeShifted: 0, volume: 80, index: 0 },
    { time: null, timeShifted: 0, volume: 80, index: 1 },
    { time: null, timeShifted: 0, volume: 80, index: 2 },
    { time: null, timeShifted: 0, volume: 80, index: 3 },
    { time: 40, timeShifted: 0, volume: 80, index: 4 },
    { time: null, timeShifted: 0, volume: 80, index: 5 },
    { time: null, timeShifted: 0, volume: 80, index: 6 },
    { time: null, timeShifted: 0, volume: 80, index: 7 },
    { time: 80, timeShifted: 0, volume: 80, index: 8 },
    { time: null, timeShifted: 0, volume: 80, index: 9 },
    { time: null, timeShifted: 0, volume: 80, index: 10 },
    { time: null, timeShifted: 0, volume: 80, index: 11 },
    { time: 120, timeShifted: 0, volume: 80, index: 12 },
    { time: null, timeShifted: 0, volume: 80, index: 13 },
    { time: null, timeShifted: 0, volume: 80, index: 14 },
    { time: null, timeShifted: 0, volume: 80, index: 15 }
  ]
];

export default demoArray;
