const demoArray = [
	[
		{ time: 0, timeShifted: 0, volume: 96, index: 0 },
		{ time: null, timeShifted: 0, volume: 80, index: 1 },
		{ time: 20, timeShifted: 0, volume: 92, index: 2 },
		{ time: null, timeShifted: 0, volume: 80, index: 3 },
		{ time: 40, timeShifted: 0, volume: 96, index: 4 },
		{ time: null, timeShifted: 0, volume: 80, index: 5 },
		{ time: 60, timeShifted: 0, volume: 86, index: 6 },
		{ time: null, timeShifted: 0, volume: 80, index: 7 },
		{ time: 80, timeShifted: 0, volume: 89, index: 8 },
		{ time: null, timeShifted: 0, volume: 80, index: 9 },
		{ time: 100, timeShifted: 0, volume: 90, index: 10 },
		{ time: null, timeShifted: 0, volume: 80, index: 11 },
		{ time: 120, timeShifted: 0, volume: 96, index: 12 },
		{ time: null, timeShifted: 0, volume: 80, index: 13 },
		{ time: null, timeShifted: 0, volume: 80, index: 14 },
		{ time: null, timeShifted: 0, volume: 80, index: 15 }
	],
	[
		{ time: null, timeShifted: 0, volume: 80, index: 0 },
		{ time: null, timeShifted: 0, volume: 80, index: 1 },
		{ time: null, timeShifted: 0, volume: 80, index: 2 },
		{ time: null, timeShifted: 0, volume: 80, index: 3 },
		{ time: null, timeShifted: 0, volume: 80, index: 4 },
		{ time: null, timeShifted: 0, volume: 80, index: 5 },
		{ time: null, timeShifted: 0, volume: 80, index: 6 },
		{ time: null, timeShifted: 0, volume: 80, index: 7 },
		{ time: null, timeShifted: 0, volume: 80, index: 8 },
		{ time: null, timeShifted: 0, volume: 80, index: 9 },
		{ time: null, timeShifted: 0, volume: 80, index: 10 },
		{ time: null, timeShifted: 0, volume: 80, index: 11 },
		{ time: null, timeShifted: 0, volume: 80, index: 12 },
		{ time: null, timeShifted: 0, volume: 80, index: 13 },
		{ time: 140, timeShifted: 0, volume: 90, index: 14 },
		{ time: null, timeShifted: 0, volume: 80, index: 15 }
	],
	[
		{ time: null, timeShifted: 0, volume: 80, index: 0 },
		{ time: null, timeShifted: 0, volume: 80, index: 1 },
		{ time: null, timeShifted: 0, volume: 80, index: 2 },
		{ time: null, timeShifted: 0, volume: 80, index: 3 },
		{ time: null, timeShifted: 0, volume: 80, index: 4 },
		{ time: null, timeShifted: 0, volume: 80, index: 5 },
		{ time: null, timeShifted: 0, volume: 80, index: 6 },
		{ time: null, timeShifted: 0, volume: 80, index: 7 },
		{ time: null, timeShifted: 0, volume: 80, index: 8 },
		{ time: null, timeShifted: 0, volume: 80, index: 9 },
		{ time: null, timeShifted: 0, volume: 80, index: 10 },
		{ time: null, timeShifted: 0, volume: 80, index: 11 },
		{ time: null, timeShifted: 0, volume: 80, index: 12 },
		{ time: null, timeShifted: 0, volume: 80, index: 13 },
		{ time: null, timeShifted: 0, volume: 80, index: 14 },
		{ time: null, timeShifted: 0, volume: 80, index: 15 }
	],
	[
		{ time: null, timeShifted: 0, volume: 80, index: 0 },
		{ time: null, timeShifted: 0, volume: 80, index: 1 },
		{ time: null, timeShifted: 0, volume: 80, index: 2 },
		{ time: null, timeShifted: 0, volume: 80, index: 3 },
		{ time: null, timeShifted: 0, volume: 80, index: 4 },
		{ time: null, timeShifted: 0, volume: 80, index: 5 },
		{ time: null, timeShifted: 0, volume: 80, index: 6 },
		{ time: null, timeShifted: 0, volume: 80, index: 7 },
		{ time: null, timeShifted: 0, volume: 80, index: 8 },
		{ time: null, timeShifted: 0, volume: 80, index: 9 },
		{ time: null, timeShifted: 0, volume: 80, index: 10 },
		{ time: null, timeShifted: 0, volume: 80, index: 11 },
		{ time: null, timeShifted: 0, volume: 80, index: 12 },
		{ time: null, timeShifted: 0, volume: 80, index: 13 },
		{ time: null, timeShifted: 0, volume: 80, index: 14 },
		{ time: null, timeShifted: 0, volume: 80, index: 15 }
	],
	[
		{ time: null, timeShifted: 0, volume: 80, index: 0 },
		{ time: null, timeShifted: 0, volume: 80, index: 1 },
		{ time: null, timeShifted: 0, volume: 80, index: 2 },
		{ time: null, timeShifted: 0, volume: 80, index: 3 },
		{ time: 40, timeShifted: 0, volume: 94, index: 4 },
		{ time: null, timeShifted: 0, volume: 80, index: 5 },
		{ time: null, timeShifted: 0, volume: 80, index: 6 },
		{ time: null, timeShifted: 0, volume: 80, index: 7 },
		{ time: null, timeShifted: 0, volume: 80, index: 8 },
		{ time: 90, timeShifted: 0, volume: 39, index: 9 },
		{ time: null, timeShifted: 0, volume: 80, index: 10 },
		{ time: null, timeShifted: 0, volume: 80, index: 11 },
		{ time: 120, timeShifted: 0, volume: 93, index: 12 },
		{ time: null, timeShifted: 0, volume: 80, index: 13 },
		{ time: null, timeShifted: 0, volume: 80, index: 14 },
		{ time: 150, timeShifted: 0, volume: 37, index: 15 }
	],
	[
		{ time: null, timeShifted: 0, volume: 80, index: 0 },
		{ time: null, timeShifted: 0, volume: 80, index: 1 },
		{ time: null, timeShifted: 0, volume: 80, index: 2 },
		{ time: null, timeShifted: 0, volume: 80, index: 3 },
		{ time: null, timeShifted: 0, volume: 80, index: 4 },
		{ time: null, timeShifted: 0, volume: 80, index: 5 },
		{ time: null, timeShifted: 0, volume: 80, index: 6 },
		{ time: null, timeShifted: 0, volume: 80, index: 7 },
		{ time: null, timeShifted: 0, volume: 80, index: 8 },
		{ time: null, timeShifted: 0, volume: 80, index: 9 },
		{ time: null, timeShifted: 0, volume: 80, index: 10 },
		{ time: null, timeShifted: 0, volume: 80, index: 11 },
		{ time: null, timeShifted: 0, volume: 80, index: 12 },
		{ time: null, timeShifted: 0, volume: 80, index: 13 },
		{ time: null, timeShifted: 0, volume: 80, index: 14 },
		{ time: null, timeShifted: 0, volume: 80, index: 15 }
	],
	[
		{ time: null, timeShifted: 0, volume: 80, index: 0 },
		{ time: null, timeShifted: 0, volume: 80, index: 1 },
		{ time: null, timeShifted: 0, volume: 80, index: 2 },
		{ time: null, timeShifted: 0, volume: 80, index: 3 },
		{ time: null, timeShifted: 0, volume: 80, index: 4 },
		{ time: null, timeShifted: 0, volume: 80, index: 5 },
		{ time: null, timeShifted: 0, volume: 80, index: 6 },
		{ time: null, timeShifted: 0, volume: 80, index: 7 },
		{ time: null, timeShifted: 0, volume: 80, index: 8 },
		{ time: null, timeShifted: 0, volume: 80, index: 9 },
		{ time: null, timeShifted: 0, volume: 80, index: 10 },
		{ time: null, timeShifted: 0, volume: 80, index: 11 },
		{ time: null, timeShifted: 0, volume: 80, index: 12 },
		{ time: null, timeShifted: 0, volume: 80, index: 13 },
		{ time: null, timeShifted: 0, volume: 80, index: 14 },
		{ time: null, timeShifted: 0, volume: 80, index: 15 }
	],
	[
		{ time: 0, timeShifted: 0, volume: 80, index: 0 },
		{ time: null, timeShifted: 0, volume: 80, index: 1 },
		{ time: null, timeShifted: 0, volume: 80, index: 2 },
		{ time: 30, timeShifted: 0, volume: 80, index: 3 },
		{ time: null, timeShifted: 0, volume: 80, index: 4 },
		{ time: null, timeShifted: 0, volume: 80, index: 5 },
		{ time: null, timeShifted: 0, volume: 80, index: 6 },
		{ time: 70, timeShifted: 0, volume: 80, index: 7 },
		{ time: null, timeShifted: 0, volume: 80, index: 8 },
		{ time: null, timeShifted: 0, volume: 80, index: 9 },
		{ time: 100, timeShifted: 0, volume: 80, index: 10 },
		{ time: null, timeShifted: 0, volume: 80, index: 11 },
		{ time: null, timeShifted: 0, volume: 80, index: 12 },
		{ time: null, timeShifted: 0, volume: 80, index: 13 },
		{ time: null, timeShifted: 0, volume: 80, index: 14 },
		{ time: null, timeShifted: 0, volume: 80, index: 15 }
	]
];

export default demoArray;
